// Generated by CoffeeScript 1.3.3
(function() {
   $(function() {
       // create our UxManager, with it driving the main loop
       // but UxViews driving decisions
       var manager = new sugs.ux.UxManager();
       
       // ..
       
       // game logic stuff .. this gets pushed into the intro_view's
       // handler for whatever button launches the map..
       //var map_size = 256;
       //var game_map = ss0.game.map.generate_height_map(map_size, map_size);
       // create our map_view
       //map_view = ss0.map_view.init(game_map);
       
       // makes the provided view "active"
       var intro_view = ss0.intro_view.init();
       manager.push_view(intro_view);
       manager.start();
     });
 }).call(this);
