// Generated by CoffeeScript 1.3.3
(function() {
  var sys_exit, sys_log, sys_log_init, sys_log_levels;

  sys_exit = function() {
    return window.close();
  };

  sys_log_levels = {
    DEBUG: 0,
    INFO: 1,
    WARN: 2,
    ERROR: 3,
    FATAL: 4
  };

  sys_log_init = function(log_config) {};

  sys_log = function(log_level, msg) {};

  var global = this;
  global.sugs = global.sugs || {};
  global.sugs.sys = {
    exit: sys_exit,
    log_init: sys_log_init
  };
}).call(this);
