// Generated by CoffeeScript 1.3.3
(function() {
  var local_bei = function(params, position) {
    var camera;
    //camera = new THREE.OrthographicCamera(params[0], params[1], params[2], params[3], params[4], params[5]);
    camera = new THREE.PerspectiveCamera(45, window.width/window.height, 1, 100000);
    camera.position.x = position.x;
    camera.position.y = position.y;
    camera.position.z = position.z;
    return camera;
  };

  var local_grp = function(origin, radius, degrees, height_offset) {
    var origin_height = origin.y;
    if (degrees === 0) {
      degrees = 1;
    }
    if (degrees > 360) {
      degrees = degrees % 360;
    }
    var radians = ss0.math_util.deg2rad(degrees);
    var x = radius * Math.cos(radians) + origin.x;
    var z = radius * Math.sin(radians) + origin.z;
    return {
      x: x,
      y: height_offset+origin.y,
      z: z
    };
  };
  sugs.namespace.set(this, 'ss0.map_view.gfx.camera', function(camera) {
    camera.birds_eye_init = local_bei;
    camera.get_radial_pos = local_grp;
  });
}).call(this);
